vision_feature_dim: &vision_feature_dim 512
low_obs_dim: &low_obs_dim 8
obs_dim: 520
action_dim: 8

obs_horizon: 2
pred_horizon: 16
action_horizon: 8

batch_size: 64
num_epochs: 5001
num_diffusion_iters: 100


num_eval: 100
max_steps: 80

rand: False


