vision_feature_dim: &vision_feature_dim 512
low_obs_dim: &low_obs_dim 2
obs_dim: 514
action_dim: 2

obs_horizon: 2
pred_horizon: 16
action_horizon: 8

batch_size: 128
num_epochs: 5001
num_diffusion_iters: 100


num_eval: 10
max_steps: 200


